Changed defualt for enable_create_defaults
philips-software/terraform-aws-vpc pull request #16
Opened 2019-10-24 07:24 UTC by npalm

Fix #15 

Disables enable_create_defaults since it impacts default resources.

2019-11-01 06:46 UTC, gertjanmaas commented
Should we even keep the `enable_create_defaults` feature?
If we expose the `default_network_acl_id` and `default_route_table_id`, users can manage the resources that would be created by this feature themselves.

2019-11-01 06:47 UTC, gertjanmaas requested changes

2019-11-01 06:47 UTC, gertjanmaas commented on variables.tf
> +  description = "Add tags to the default resources."
This description doesn't say that much to me.
```suggestion
  description = "Replaces AWS default network ACL, security group and routing table with module resources"
```

2019-11-04 07:48 UTC, npalm commented
> Should we even keep the `enable_create_defaults` feature?
> If we expose the `default_network_acl_id` and `default_route_table_id`, users can manage the resources that would be created by this feature themselves.

Yes I agree, therefor I would say as first step we remove the behaviour by default. In this case we keep the module compatible. We have projects using this feature right now.

2019-11-13 10:28 UTC, gertjanmaas approved these changes

2019-11-13 11:51 UTC, merged